name: CI

on: [push]

on:
  push:
    branches:
      - master
    paths:
      - 'markdown/*'

    runs-on: ubuntu-latest
    
    steps:
    - name: Stoplight API Request
      uses: actions/bin/curl@master
      with:
        args: ["${{ secrets.SL_AUTH_HEADER }} -x POST https://next-api.stoplight.io/docs.release?id=890"]
